### ISSUE TITLE
README for redefining extension gallery URLs

### ISSUE THREAD

**Issue by parcelcat** [flathub/com.visualstudio.code-oss#11]
I noticed that the default extension gallery was switched from the Visual Studio Marketplace to Open VSX in 7a59343606ce105d096f84d7477c5313477cd2eb, and that the environment variable `VSCODE_EXTENSIONS_GALLERY` is used to specify a user-defined extension gallery in f4fb6f33f410a59a04a5b564792e024b524fd2cc.

However, it's unclear what `VSCODE_EXTENSIONS_GALLERY` needs to contain, and whether any other files are required to make Code - OSS set the user-defined extension gallery. Perhaps a README file could explain this?

**Comment by gasinvein** [comment]
The env var is expected to contain path to a `json` file with a single object defining extension gallery, similar to the one in `extensionsGallery` field of `/app/main/resources/app/product.json`, e.g. `/absolute/path/to/vscode-gallery.json` file containing
```json
{
    "serviceUrl": "https://open-vsx.org/vscode/gallery",
    "itemUrl": "https://open-vsx.org/vscode/item"
}
```
This is not yet documented because it's not ready for end users and may be changed in future, and also I'm still hoping to get a clear answer from MS if unofficial VS Code builds are allowed to use official extensions gallery.

**Comment by articlecat** [comment]
Thank you, it works perfectly with the `extensionsGallery` values specified in microsoft/vscode#31168.

Microsoft has not responded since that issue was opened in July 2017, so Microsoft will probably never comment on whether this is allowed. The values were published under the MIT License, and I don't think the MIT License is revocable. Arch Linux [has been using these values](https://github.com/archlinux/svntogit-community/blob/packages/code/trunk/product_json.diff) in its Code package (which is [in the official community repository](https://www.archlinux.org/packages/community/x86_64/code/)) since April 2019 with no issues.

**Comment by gasinvein** [comment]
@articlecat IANAL, but the problem is not gallery URLs, it's the Marketplace ToS, which only allows using it with "Visual Studio products". That is, while we probably could put official marketplace URLs in this build, it's unclear if one who installed would be allowed to actually use it.

**Comment by articlecat** [comment]
It's certainly a gray area. Thanks for including the environment variable as a option.

**Comment by rugk** [comment]
Well… documenting [the thing you already included won't hurt](https://github.com/flathub/com.visualstudio.code-oss/commit/f4fb6f33f410a59a04a5b564792e024b524fd2cc), will it?

Basically do this:
* At `$HOME/.var/app/com.visualstudio.code-oss/config` create a JSON file, e.g. named `product.json`.
* Enter [the correct URLs the VSCodium upstream project documents](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace):
  ```json
  {
      "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
      "itemUrl": "https://marketplace.visualstudio.com/items"
  }
  ```
* Now override the flatpak to include that environment variable `sudo flatpak override --env=VSCODE_EXTENSIONS_GALLERY=$HOME/.var/app/com.visualstudio.code-oss/config/product.json com.visualstudio.code-oss`
  Yes, it requires root permissions to do that.
* Now you can start the flatpak as usual (no need for command line stuff)

However, if it does not start, start it from the command line (`flatpak run com.visualstudio.code-oss`) and you'll see potential errors thrown there, e.g. if the path to the file is wrong.

**Comment by gasinvein** [comment]
>Yes, it requires root permissions to do that

Well, no. You can pass `--user` option to make per-user override.

**Comment by rugk** [comment]
Okay thanks, did not know that. Then I've just set it for the whole system, also does not hurt. :slightly_smiling_face:

**Comment by gasinvein** [comment]
Code-OSS flatpak-specific patch for redefining the gallery was replaced by VSCodium's patch. You can now follow the VSCodium's [guide](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) on how to configure it (replace `VSCodium` with `Code - OSS` in file paths etc in the guide).
In short, you'll need to create the `~/.var/app/com.visualstudio.code-oss/config/Code - OSS/product.json` file.
